sudo: required
dist: trusty

language: cpp

compiler:
 - clang
 - gcc

script:
 - mkdir _build
 - cd _build
 - cmake ..
 - make
 - bin/utee-runner bin/libagge.tests.so
 - bin/utee-runner bin/libagge.text.tests.so
 - bin/utee-runner bin/libagge.async.tests.so
